### ISSUE TITLE
Copy Markdown to Formatted HTML to Clipboard broken

### ISSUE THREAD

**Issue by tmthywynn8** [Andre9642/nvda-markdownForever#14]
When using NVDA 2022.1 with Markdown Forever 22.05.19:e6481b4, I get the following error when trying to convert to formatted HTML:

~~~
ERROR - scriptHandler.executeScript (18:33:50.381) - MainThread (3800):
error executing script: <bound method GlobalPlugin.script_copyFormattedHTMLToClip of <globalPlugins.markdownForever.GlobalPlugin object at 0x06CE34D0>> with gesture 'shift+NVDA+h'
Traceback (most recent call last):
  File "scriptHandler.pyc", line 216, in executeScript
  File "...\addons\markdownForever\globalPlugins\markdownForever\__init__.py", line 238, in script_copyFormattedHTMLToClip
    if copyToClipAsHTML(convertToHTML(text, metadata, src=True, display=False, save=False)):
NameError: name 'copyToClipAsHTML' is not defined
~~~

**Comment by tmthywynn8** [comment]
Ah.  Line 30 is supposed to read: `convertToHTML, convertToMD, copyToClipAsHTML,`

**Comment by AAClause** [comment]
Thank you! Introduced in 5085060, fixed it. :)
